services:
  db:
    image: mysql:8.0
    container_name: marketplace_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: marketplace_secret_pw
      MYSQL_DATABASE: marketplace_db
      MYSQL_USER: marketplace_user
      MYSQL_PASSWORD: marketplace_secret_pw
    ports:
      - "3307:3306"
    volumes:
      - marketplace_mysqldata:/var/lib/mysql
      - ./apps/backend_api/database/init_mysql.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD --silent"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - marketplace_net

  api:
    build:
      context: .
      dockerfile: apps/backend_api/Dockerfile
    container_name: marketplace_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 8080
      HOST: 0.0.0.0
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: marketplace_db
      DB_USER: marketplace_user
      DB_PASSWORD: marketplace_secret_pw
    ports:
      - "8080:8080"
    networks:
      - marketplace_net

volumes:
  marketplace_mysqldata:
    driver: local
  marketplace_pgdata:
    driver: local

networks:
  marketplace_net:
    driver: bridge
